name: Release

on:
  push:
    tags:
      - 'v[0-9].[0-9].[0-9]'

jobs:
  build_release_binaries:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-13
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
        toolchain:
          - stable
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: sudo apt-get install protobuf-compiler
      - run: cargo build --release --all-features
      - uses: actions/upload-artifact@v4
        with:
          name: cedar-${{matrix.target}}
          path: ./target/release/cedar
