name: Release

on:
  push:
    tags:
      - 'v[0-9].[0-9].[0-9]'

jobs:
  build_release_binaries:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, macos-latest]
        toolchain:
          - stable
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --release --all-features
      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: cedar-{{matrix.os}}
          


        
  